-- AlterTable
ALTER TABLE "ESTUDIANTES" ALTER COLUMN "fecha_nacimiento" SET DATA TYPE DATE,
ALTER COLUMN "fecha_registro" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "INSCRIPCIONES" ALTER COLUMN "fecha_inscripcion" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "PROFESORES" ADD COLUMN     "activo" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "fecha_contrato" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "SESIONES" ALTER COLUMN "fecha" SET DATA TYPE DATE;
